'use strict';
const api=window.desktop,core=window.SamaCore,content=document.querySelector('#content');
const pages=['Accueil','Recherche','Ma liste','Reprendre','Sources','Directs sportifs','Réglages'];
let state=core.fresh(),page='Accueil',query='',category='Tous',revision=0,playback=null,saveTimer,deadline=0,lastInteraction=Date.now(),dimmed=false,focusMemory=new Map(),remoteSnapshot=null;
const element=(tag,text,parent,className)=>{const n=document.createElement(tag==='select'?'sama-select':tag);if(text)n.textContent=text;if(className)n.className=className;parent?.append(n);return n};
function button(label,parent,action){const n=element('button',label,parent);n.type='button';n.onclick=()=>{Promise.resolve().then(action).catch(error=>message(error.message))};return n;}
function message(text,parent=content){let n=parent.querySelector('.feedback');if(!n){n=element('p','',parent,'feedback');n.setAttribute('role','status')}n.textContent=text;}
function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>api.save(state).catch(e=>message(`Sauvegarde impossible : ${e.message}`)),150);}
function itemState(item){return state.items.find(x=>core.same(x,item));}
function resumeFor(item){const language=item.selectedLanguage||state.settings.language,episodes=(item.episodes||[]).filter(e=>!e.language||e.language==='UNKNOWN'||e.language===language);return core.resumeEpisode(state,{...item,episodes});}
const preloaded=new Map();
api.onMediaError?.(data=>{if(playback?.token===data.token)playback.mediaError=data.message;});
const playbackKey=(item,episode)=>`${item.provider}|${item.id}|${episode?.id||''}`;
api.onCommand(command=>{if(command.action==='librarySync'){core.mergeHistory(state,command.history||[]);for(const [key,time]of Object.entries(command.hidden||{}))state.hidden[key]=Math.max(state.hidden[key]||0,time);persist();if(page==='Reprendre'&&!playback)render()}});
api.onCommand(command=>{if(command.action==='preload'&&command.anime&&command.sources?.length){if(preloaded.size>=4)preloaded.delete(preloaded.keys().next().value);preloaded.set(playbackKey(command.anime,command.episode),{sources:command.sources,until:Date.now()+120000})}else if(command.action==='episode'&&playback){const episode=playback.item.episodes?.find(e=>e.id===command.episode?.id);if(episode)start(playback.item,episode,undefined,true).catch(e=>message(e.message))}});
function rememberItem(item){let saved=itemState(item);if(saved){const favorite=saved.favorite;Object.assign(saved,item,{favorite});return saved}saved={...item,favorite:false};state.items.push(saved);return saved;}
function progress(item,episode){return state.history.find(e=>core.same(e.anime,item)&&(item.tag==='Film'||e.episodeId===episode?.id||(e.season===(episode?.season||episode?.seasonNumber)&&e.number===episode?.number)));}
function savePosition(){if(!playback)return;const p=playback;core.saveProgress(state,p.item,p.episode,p.video.currentTime*1000,p.video.duration*1000);persist();}
function teardown(){if(!playback)return;savePosition();const p=playback;playback=null;clearInterval(p.tick);p.video.pause();p.hls?.destroy();p.dash?.reset();if(p.token)api.releaseMedia(p.token).catch(()=>{});p.video.removeAttribute('src');p.video.load();content.classList.remove('dimmed');dimmed=false;}
async function navigate(next){if(document.activeElement?.dataset.focus)focusMemory.set(page,document.activeElement.dataset.focus);teardown();page=next;revision++;await Promise.all(['catalog','details','resolve','live'].map(id=>api.cancel(id)));await render();}
function image(url,title,parent){if(!url||!/^https:\/\//.test(url))return;const img=element('img','',parent);img.src=url;img.alt=title;img.loading='lazy';img.decoding='async';img.onerror=()=>img.remove();}
function cards(items,parent){const grid=element('div','',parent,'grid');for(const item of items.slice(0,120)){const card=button('',grid,()=>details(item));card.className='card';card.dataset.focus=`${item.provider}|${item.id}`;image(item.poster,item.title,card);element('strong',item.title,card);element('span',`${item.tag||'Film'} · ${item.references?.length>1?`${item.references.length} sources`:item.provider||'Personnel'}`,card);}if(!items.length)element('p','Aucun titre disponible.',parent);const target=focusMemory.get(page);if(target&&!document.activeElement.matches('input,textarea')){const found=[...grid.querySelectorAll('button')].find(n=>n.dataset.focus===target);found?.focus()}}
function libraryCards(items,parent){let offset=0;const draw=()=>{parent.replaceChildren();cards(items.slice(offset,offset+120),parent);if(items.length<=120)return;const row=element('div','',parent,'toolbar');const previous=button('Page précédente',row,()=>{offset=Math.max(0,offset-120);draw();parent.querySelector('button')?.focus()});previous.disabled=offset===0;element('span',`${offset+1}–${Math.min(offset+120,items.length)} / ${items.length}`,row);const next=button('Page suivante',row,()=>{offset+=120;draw();parent.querySelector('button')?.focus()});next.disabled=offset+120>=items.length;};draw();}
function renderPersonal(){const parent=document.querySelector('#personalResults');if(!parent)return;const normalize=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const words=normalize(page==='Recherche'?query:'').split(/\s+/).filter(Boolean);const tags={'Films':'Film','Séries':'Série','Animation':'Animation','TV en direct':'Direct'};libraryCards(state.items.filter(item=>item.provider==='Personnel'&&(!tags[category]||item.tag===tags[category])&&words.every(word=>normalize(item.title).includes(word))),parent);}
function returnToDetails(item,episode){teardown();revision++;api.cancel('resolve');api.cancel('details');showDetails(item,episode);}
function rememberSearch(value){if(!value.trim())return;state.searches=[value.trim(),...state.searches.filter(x=>x.toLowerCase()!==value.trim().toLowerCase())].slice(0,12);persist();}
async function render(){const mine=++revision;content.replaceChildren();document.querySelectorAll('nav button').forEach(n=>n.setAttribute('aria-current',n.textContent===page?'page':'false'));element('h2',page,content);document.body.classList.toggle('oled',state.settings.oled);document.body.classList.toggle('compact',state.settings.density==='Compact');
 if(page==='Sources'){return renderSources(mine)}if(page==='Réglages'){renderSettings();return}if(page==='Directs sportifs'){return renderLive(mine)}
 if(page==='Ma liste'){libraryCards(state.items.filter(x=>x.favorite),content);return}if(page==='Reprendre'){for(const entry of core.continuing(state)){const row=element('div','',content,'resume');const next=core.resumeEpisode(state,entry.anime);button(`${entry.anime.title} · S${entry.season} E${entry.number} · ${Math.floor(entry.position/60000)} min`,row,()=>details(entry.anime,next));button('Retirer de Reprendre',row,()=>{state.hidden[core.key(entry.anime)]=Date.now();persist();render()})}return}
 if(page==='Recherche'){const input=element('input','',content);input.type='search';input.placeholder='Film, série, animation…';input.setAttribute('aria-label','Rechercher');input.value=query;let timer;input.oninput=()=>{clearTimeout(timer);query=input.value;api.cancel('catalog');timer=setTimeout(()=>loadCatalog(1,true),300)};input.onkeydown=e=>{if(e.key==='Enter'){clearTimeout(timer);rememberSearch(input.value);loadCatalog(1,true)}};const recent=element('div','',content,'toolbar');for(const term of state.searches)button(term,recent,()=>{query=term;input.value=term;rememberSearch(term);loadCatalog(1,true)});input.focus();}
 const categories=element('div','',content,'toolbar');for(const name of ['Tous','Films','Séries','Animation','TV en direct']){const n=button(name,categories,()=>{category=name;for(const control of categories.querySelectorAll('button'))control.setAttribute('aria-pressed',String(control.textContent===name));return loadCatalog(1,true)});n.setAttribute('aria-pressed',String(category===name))}
 if(page==='Accueil'&&core.continuing(state).length){element('h3','Reprendre',content);cards(core.continuing(state).slice(0,6).map(e=>e.anime),content)}
 if(state.items.some(x=>x.provider==='Personnel')){element('h3','Mes flux',content);const personal=element('div','',content);personal.id='personalResults';renderPersonal()}
 const results=element('div','',content);results.id='catalogResults';element('p','Chargement du catalogue…',results);await loadCatalog(1,true,mine);
}
let catalogRequest=0,loaded=[],catalogOffset=0,catalogView=0;
api.onSourcesUpdated?.(()=>{if(playback)return;if(page==='Sources')render().catch(e=>message(e.message));else if(document.querySelector('#catalogResults'))loadCatalog(1,true)});
api.onCatalog(data=>{const results=document.querySelector('#catalogResults');if(data.requestToken!==catalogRequest||catalogView!==revision||!results)return;loaded=core.mergeCatalog([...loaded,...data.items]).slice(0,2400);catalogPages(results,data.page||1)});
function catalogPages(results,number){let offset=catalogOffset;const draw=()=>{catalogOffset=offset;const focused=results.contains(document.activeElement)?document.activeElement.dataset.focus:null;results.replaceChildren();cards(loaded.slice(offset,offset+120),results);const row=element('div','',results,'toolbar');const prev=button('Page précédente',row,()=>{offset=Math.max(0,offset-120);draw()});prev.disabled=offset===0;element('span',`${Math.min(offset+1,loaded.length)}–${Math.min(offset+120,loaded.length)} / ${loaded.length}`,row);const next=button('Page suivante',row,()=>{offset+=120;draw()});next.disabled=offset+120>=loaded.length;button('Charger la suite',row,()=>loadCatalog(number+1,false));if(focused)[...results.querySelectorAll('[data-focus]')].find(n=>n.dataset.focus===focused)?.focus();};draw();}
async function loadCatalog(number=1,reset=true,view=revision){renderPersonal();const results=document.querySelector('#catalogResults');if(!results)return;catalogView=view;const request=++catalogRequest;if(reset){loaded=[];catalogOffset=0;}try{const data=await api.catalog({query:page==='Recherche'?query:'',category,page:number,requestToken:request});if(view!==revision||request!==catalogRequest)return;loaded=core.mergeCatalog([...loaded,...data.items]).slice(0,2400);catalogPages(results,number);const failures=data.sources.filter(x=>x.ported&&x.enabled&&!/disponible/.test(x.status));if(failures.length)message(failures.map(x=>`${x.name} : ${x.status}`).join(' · '),results);}catch(e){if(view===revision&&request===catalogRequest)message(`Catalogue : ${e.message}`,results)}}
async function details(item,preferred){teardown();api.cancel('catalog');api.cancel('resolve');const mine=++revision;content.replaceChildren();element('h2',item.title,content);element('p','Chargement de la fiche…',content);try{item=await api.details(item);if(mine!==revision)return;item=rememberItem(item);persist();showDetails(item,preferred);
 }catch(e){if(mine===revision){message(e.message);button('Retour',content,()=>navigate(page))}}}
function showDetails(item,preferred){content.replaceChildren();image(item.poster,item.title,content);element('h2',item.title,content);element('p',item.description||'',content);if(item.year)element('p',String(item.year),content);if(item.genres?.length)element('p',item.genres.join(' · '),content);const row=element('div','',content,'toolbar');button('Lire / Reprendre',row,()=>start(item,preferred&&(!preferred.language||preferred.language==='UNKNOWN'||preferred.language===item.selectedLanguage)?preferred:resumeFor(item)));const favorite=button(item.favorite?'Retirer de ma liste':'Ajouter à ma liste',row,()=>{item.favorite=!item.favorite;persist();favorite.textContent=item.favorite?'Retirer de ma liste':'Ajouter à ma liste'});button('Retour',row,()=>navigate(page));const available=[...new Set((item.episodes||[]).map(e=>e.language).filter(l=>l&&l!=='UNKNOWN'))];item.selectedLanguage=available.includes(state.settings.language)?state.settings.language:available[0]||state.settings.language;const languages=element('div','',content,'toolbar');for(const language of ['VF','VOSTFR']){const n=button(language,languages,()=>{state.settings.language=language;item.selectedLanguage=language;persist();showDetails(item)});n.setAttribute('aria-pressed',String(item.selectedLanguage===language));n.disabled=available.length>0&&!available.includes(language)}
 if(item.provider==='Personnel')button('Supprimer ce flux personnel',row,()=>{state.items=state.items.filter(x=>x!==item);persist();navigate('Sources')});
 if(item.references?.length>1){const choices=element('div','',content,'toolbar');for(const ref of item.references){const choice=button(`Source : ${ref.provider}`,choices,()=>details({...item,...ref,raw:undefined,url:undefined,episodes:[]}));choice.setAttribute('aria-pressed',String(ref.provider===item.provider&&ref.id===item.id));}}
 if(!item.episodes?.length||item.tag==='Film'||item.tag==='Direct'){if(item.tag==='Série'){row.querySelector('button').disabled=true;message('Aucun épisode disponible sur cette source. Choisissez une autre source ou réessayez.');button('Réessayer la fiche',content,()=>details(item,preferred));}row.querySelector('button:not(:disabled)')?.focus();return;}
 const episodes=(item.episodes||[]).filter(e=>e.language==='UNKNOWN'||!e.language||e.language===item.selectedLanguage);const seasons=[...new Set(episodes.map(e=>e.season||e.seasonNumber||1))];const select=element('select','',content);select.setAttribute('aria-label','Saison');for(const season of seasons){const o=element('option',`Saison ${season}`,select);o.value=String(season)}const resume=episodes.find(e=>e.id===preferred?.id)||episodes.find(e=>e.number===preferred?.number&&(e.season||e.seasonNumber)===(preferred?.season||preferred?.seasonNumber))||resumeFor(item);if(resume)select.value=String(resume.season||resume.seasonNumber||1);const list=element('div','',content,'episodes');let episodeOffset=0;const show=()=>{list.replaceChildren();const entries=episodes.filter(e=>(e.season||e.seasonNumber||1)===Number(select.value));for(const episode of entries.slice(episodeOffset,episodeOffset+120)){const saved=progress(item,episode);const n=button(`${episode.number} · ${episode.title}${saved?core.finished(saved)?' · Vu':` · ${Math.floor(saved.position/60000)} min`:''}`,list,()=>start(item,episode));if(episode.id===resume?.id)n.setAttribute('aria-current','true')}if(episodeOffset>0)button('Épisodes précédents',list,()=>{episodeOffset-=120;show()});if(episodeOffset+120<entries.length)button('Épisodes suivants',list,()=>{episodeOffset+=120;show()})};select.onchange=()=>{episodeOffset=0;show()};show();row.querySelector('button')?.focus();
}
async function renderSources(mine){button('Ajouter un flux',content,()=>{document.querySelector('#formError').textContent='';document.querySelector('#add').showModal();document.querySelector('#title').focus()});button('Actualiser l’annuaire',content,async()=>{const result=await api.directory();if(mine===revision){message(result.changed.length?`Adresses réparées : ${result.changed.join(', ')}`:'Annuaire à jour.');}});const sources=await api.sources();if(mine!==revision)return;for(const source of sources){const row=element('div','',content,'source-row');element('strong',source.name,row);element('span',source.status,row);const toggle=button(source.enabled?'Désactiver':'Activer',row,async()=>{await api.sourceToggle(source.name,!source.enabled);const data=await api.bootstrap();state.disabled=data.state.disabled;state.addresses=data.state.addresses;render()});toggle.disabled=!source.ported;if(source.ported&&source.kind!=='m3u')button('Ouvrir l’accès au site',row,()=>api.sourceAccess(source.name));}cards(state.items.filter(x=>x.provider==='Personnel'),content)}
function selectSetting(label,key,values){const row=element('label',label,content,'setting');const select=element('select','',row);select.setAttribute('aria-label',label);for(const [value,title]of values){const n=element('option',title,select);n.value=String(value)}select.value=String(state.settings[key]);select.onchange=()=>{const value=values.find(v=>String(v[0])===select.value)?.[0];state.settings[key]=value;persist();document.body.classList.toggle('oled',state.settings.oled);document.body.classList.toggle('compact',state.settings.density==='Compact');if(key==='viewScale')api.scale(value).catch(e=>message(e.message));if(key==='dns')api.dns(value).then(()=>message('Résolution DNS appliquée. Réessayez la source.')).catch(e=>message(e.message))};}
function renderSettings(){selectSetting('Résolution DNS','dns',[['system','Système'],['cloudflare','Cloudflare (comme Android)'],['google','Google']]);selectSetting('Taille de l’interface','viewScale',[[.75,'75 %'],[1,'100 %'],[1.25,'125 %'],[1.5,'150 %'],[1.75,'175 %'],[2,'200 %']]);selectSetting('Langue préférée','language',[['VF','VF'],['VOSTFR','VOSTFR']]);for(const [label,key]of [['Épisode suivant','autoplay'],['Sous-titres','subtitles'],['Assombrissement en pause','pauseDimming'],['Fond OLED','oled'],['Animations','motion']])selectSetting(label,key,[[true,'Activé'],[false,'Désactivé']]);selectSetting('Minuterie','sleepMinutes',[0,60,90,120,150,180].map(v=>[v,v?`${v} min`:'Désactivée']));selectSetting('Densité','density',[['Confort','Confort'],['Compact','Compact']]);selectSetting('Écran au lancement','startup',pages.slice(0,4).map(v=>[v,v]));
 button('Crédits et licences',content,async()=>{const notices=await api.licenses(),dialog=element('dialog','',document.body);element('h2','Crédits et licences',dialog);button('Fermer',dialog,()=>dialog.close());const text=element('pre',notices.map(x=>`${x.name}\n\n${x.text}`).join('\n\n'),dialog);text.style.whiteSpace='pre-wrap';dialog.onclose=()=>dialog.remove();dialog.showModal()});
 element('p','Dictée Windows : sélectionnez le champ Recherche, puis appuyez sur Windows + H pour dicter un titre.',content);
 button('Exporter ma bibliothèque',content,async()=>{if(await api.backupExport())message('Sauvegarde enregistrée.')});button('Restaurer une sauvegarde Android / Windows',content,async()=>{const incoming=await api.backupImport();if(incoming){state=incoming;render()}});button('Effacer l’historique',content,()=>{for(const e of state.history)state.hidden[core.key(e.anime)]=Date.now();state.history=[];persist();message('Historique effacé.')});
 const tmdb=element('label','Token TMDB personnel (facultatif)',content);const input=element('input','',tmdb);input.type='password';input.autocomplete='off';button('Enregistrer TMDB',tmdb,()=>{state.settings.tmdbToken=input.value.trim();input.value='';persist();message('Préférence enregistrée.')});
 button('Afficher le QR de ce PC',content,async()=>{const pairing=await api.pairing();const box=element('div','',content,'pairing');const img=element('img','',box);img.src=pairing.qr;img.alt='QR d’association TvSama';element('p','Scannez avec le téléphone sur le même réseau Wi-Fi.',box)});
 const pairLabel=element('label','Associer une TV (code tvsama://pair…)',content);const pairInput=element('input','',pairLabel);button('Associer',pairLabel,async()=>{await api.pair(pairInput.value);message('Télévision associée.');pairInput.value=''});
 const remoteRow=element('div','',content,'toolbar');for(const [label,action]of [['Lecture / Pause TV','toggle'],['Épisode précédent TV','previous'],['Épisode suivant TV','next'],['Relancer 3 h TV','sleep']])button(label,remoteRow,()=>api.remote({action}));button('Synchroniser avec la TV',content,async()=>{remoteSnapshot=await api.remote({action:'sync',history:state.history.slice(0,100),hidden:state.hidden});core.mergeHistory(state,remoteSnapshot.history||[]);for(const [key,time]of Object.entries(remoteSnapshot.hidden||{}))state.hidden[key]=Math.max(state.hidden[key]||0,time);persist();message(`Synchronisé · ${remoteSnapshot.playback?.title||'TV'}`)});
 const qrLabel=element('label','Lire le QR d’une TV depuis une image',content),qrInput=element('input','',qrLabel);qrInput.type='file';qrInput.accept='image/*';qrInput.onchange=async()=>{try{const file=qrInput.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('Image limitée à 10 Mo');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>16000000){bitmap.close();throw Error('Image trop grande')}const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0);bitmap.close();const image=ctx.getImageData(0,0,canvas.width,canvas.height),qr=jsQR(image.data,image.width,image.height);if(!qr)throw Error('Aucun QR lisible dans cette image');await api.pair(qr.data);message('Télévision associée depuis son QR.')}catch(e){message(e.message)}finally{qrInput.value=''}};
 button('Vérifier les mises à jour',content,async()=>{const update=await api.checkUpdate();message(`Version publiée : ${update.version}${update.url?'':' · Aucun EXE joint'}`);if(update.digest)button('Télécharger et vérifier l’EXE',content,async()=>{message('Téléchargement et vérification SHA-256…');const saved=await api.downloadUpdate();if(saved)message(`${saved.file} vérifié. Fermez TvSama puis lancez ce fichier.`)});else if(update.url)button('Ouvrir le téléchargement Windows',content,()=>api.openUpdate(update.url))});element('p','TvSama · Adaptateurs issus de StreamFlix Reborn (Apache 2.0). Crédits et licences inclus dans le dossier licenses du paquet.',content);
}
async function renderLive(mine){button('Actualiser',content,()=>render());element('p','Chargement du calendrier…',content);try{const events=await api.live();if(mine!==revision)return;for(const label of ['En direct','À venir']){element('h3',label,content);const group=events.filter(e=>label==='En direct'?e.isLive:!e.isLive&&e.startsAt>Date.now());if(!group.length)element('p','Aucun programme publié dans cette catégorie.',content);for(const event of group){const row=element('div','',content,'source-row');element('strong',event.title,row);element('p',`${new Date(event.startsAt).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})} · ${event.competition}`,row);if(event.isLive)button('Regarder',row,()=>start({id:event.url,title:event.title,provider:'Volkamax',tag:'Direct',episodes:[]},{id:event.url,title:event.title,number:1,season:1}));else button(state.reminders?.[event.id]?'Annuler le rappel':'Rappel 10 min avant',row,async()=>{state.reminders=await api.reminder(event);render()})}}}catch(e){if(mine===revision)message(e.message)}}
async function start(item,episode,supplied,continuation=false,fresh=false){teardown();api.cancel('catalog');api.cancel('details');const mine=++revision;content.replaceChildren();element('h2',item.title,content);element('p','Résolution des serveurs…',content);try{const cached=preloaded.get(playbackKey(item,episode));const sources=supplied||(!fresh&&cached?.until>Date.now()?cached.sources:null)||await api.resolve(item,episode,{refresh:fresh});if(mine!==revision)return;if(!deadline&&!continuation)deadline=state.settings.sleepMinutes?Date.now()+state.settings.sleepMinutes*60000:0;await attach(item,episode,sources,0,mine,undefined,fresh);}catch(e){if(mine===revision){message(e.message);button('Réessayer la lecture',content,()=>start(item,episode,undefined,true,true));button('Retour à la fiche',content,()=>returnToDetails(item,episode))}}}
async function attach(item,episode,sources,index,mine,resumePosition,refreshed=false){if(mine!==revision)return;const source=sources[index];if(!source)throw Error('Tous les serveurs ont échoué');const media=await api.media(source);if(mine!==revision){api.releaseMedia(media.token);return}content.replaceChildren();element('h2',`${item.title}${episode?` · ${episode.title}`:''}`,content);const video=element('video','',content);video.controls=true;video.playsInline=true;video.setAttribute('aria-label','Lecteur vidéo');const error=element('p','',content,'feedback');const row=element('div','',content,'toolbar');
 const p={video,item,episode,sources,index,source,token:media.token,savedAt:0,segments:null};playback=p;lastInteraction=Date.now();
 const retry=button('Renouveler les serveurs',row,()=>start(item,episode,undefined,true,true));retry.hidden=true;
 const seek=seconds=>{if(Number.isFinite(video.duration))video.currentTime=Math.max(0,Math.min(video.duration,video.currentTime+seconds))};button('−15 s',row,()=>seek(-15));button('Lecture / Pause',row,()=>video.paused?video.play():video.pause());button('+15 s',row,()=>seek(15));button('Plein écran',row,()=>video.requestFullscreen());button('PiP',row,()=>video.requestPictureInPicture?video.requestPictureInPicture():Promise.reject(Error('PiP indisponible sur ce système')));button('Retour',row,()=>returnToDetails(item,episode));
 const server=element('select','',row);server.setAttribute('aria-label','Serveur');sources.forEach((s,i)=>{const n=element('option',`${s.name||`Serveur ${i+1}`} · ${s.language||'UNKNOWN'}`,server);n.value=i});server.value=index;server.onchange=()=>{const target=Number(server.value),position=video.currentTime;teardown();const request=++revision;return attach(item,episode,sources,target,request,position,refreshed).catch(e=>{if(request===revision)message(e.message)})};
 const ordered=(item.episodes||[]).filter(e=>!e.language||e.language==='UNKNOWN'||e.language===(episode?.language&&episode.language!=='UNKNOWN'?episode.language:item.selectedLanguage||state.settings.language)).filter((e,i,a)=>a.findIndex(x=>(x.season||x.seasonNumber)===(e.season||e.seasonNumber)&&x.number===e.number)===i);const current=ordered.findIndex(e=>e.id===episode?.id);p.previous=current>0?ordered[current-1]:null;p.next=current>=0?ordered[current+1]:null;const prev=button('Épisode précédent',row,()=>start(item,p.previous,undefined,true));prev.disabled=!p.previous;const next=button('Épisode suivant',row,()=>start(item,p.next,undefined,true));next.disabled=!p.next;
 button('Sur ma TV associée',row,async()=>{await api.remote({action:'play',anime:item,episode,sources,language:state.settings.language});video.pause();message('Lecture envoyée à la TV.')});button('Chercher les appareils Cast',row,async()=>{const devices=await api.castDiscover();if(!devices.length)message('Recherche Cast démarrée. Réessayez dans quelques secondes.');for(const device of devices)button(device.name,row,async()=>{await api.castLoad(device.host,{...source,title:item.title},video.currentTime*1000);video.pause();message('Lecture sur Cast.');button('Reprendre ici',row,async()=>{const status=await api.castCommand('status');await api.castStop();video.currentTime=status.currentTime||video.currentTime;video.play()})})});
 const quality=element('span','Qualité : détection…',row);video.onresize=()=>quality.textContent=`Qualité : ${video.videoHeight||'?'}p`;const skip=button('Passer l’intro / outro',row,()=>{const segment=Object.values(p.segments||{}).find(s=>s&&video.currentTime*1000>=s.start&&video.currentTime*1000<s.end);if(segment)video.currentTime=segment.end/1000});skip.hidden=true;
 const saved=progress(item,episode);video.addEventListener('loadedmetadata',()=>{if(Number.isFinite(video.duration)){if(Number.isFinite(resumePosition))video.currentTime=Math.max(0,Math.min(resumePosition,Math.max(0,video.duration-1)));else if(saved&&!core.finished(saved))video.currentTime=Math.min(saved.position/1000,Math.max(0,video.duration-1));}video.play().catch(e=>error.textContent=e.message)},{once:true});
 const fail=()=>{if(playback!==p)return;const position=video.currentTime;savePosition();if(index+1<sources.length){teardown();const request=++revision;attach(item,episode,sources,index+1,request,position,refreshed).catch(e=>{if(request===revision)message(e.message)})}else if(!refreshed&&!item.url){error.textContent='Renouvellement des serveurs…';start(item,episode,undefined,true,true);}else{retry.hidden=false;error.textContent='Tous les serveurs ont échoué. '+(p.mediaError||'Réessayez ou vérifiez l’accès à la source.')}};video.onerror=fail;
 if(((media.format||source.format)==='hls'||/\.m3u8(?:[?#]|$)/i.test(source.url))&&Hls.isSupported()){p.hls=new Hls({maxBufferLength:30,maxMaxBufferLength:60,backBufferLength:30});p.hls.loadSource(media.url);p.hls.attachMedia(video);p.hls.on(Hls.Events.ERROR,(_e,data)=>{if(data.fatal)fail()});p.hls.on(Hls.Events.MANIFEST_PARSED,()=>{const q=element('select','',row);q.setAttribute('aria-label','Qualité vidéo');element('option','Automatique',q).value=-1;p.hls.levels.forEach((l,i)=>element('option',l.height?`${l.height}p`:`Niveau ${i+1}`,q).value=i);q.onchange=()=>p.hls.currentLevel=Number(q.value)});p.hls.on(Hls.Events.AUDIO_TRACKS_UPDATED,()=>{if(!p.hls.audioTracks.length)return;const audio=element('select','',row);audio.setAttribute('aria-label','Piste audio');p.hls.audioTracks.forEach((t,i)=>element('option',t.name||t.lang||`Piste ${i+1}`,audio).value=i);audio.onchange=()=>p.hls.audioTrack=Number(audio.value)});}
 else if(((media.format||source.format)==='dash'||/\.mpd(?:[?#]|$)/i.test(source.url))&&window.dashjs){p.dash=dashjs.MediaPlayer().create();p.dash.initialize(video,media.url,false);p.dash.on(dashjs.MediaPlayer.events.ERROR,fail)}else video.src=media.url;
 if(p.hls)p.hls.on(Hls.Events.SUBTITLE_TRACKS_UPDATED,()=>{let subtitles=row.querySelector('[data-subtitles]');if(!subtitles){subtitles=element('select','',row);subtitles.dataset.subtitles='true';subtitles.setAttribute('aria-label','Sous-titres');}subtitles.replaceChildren();element('option','Désactivés',subtitles).value=-1;p.hls.subtitleTracks.forEach((t,i)=>element('option',t.name||t.lang||`Piste ${i+1}`,subtitles).value=i);subtitles.value=state.settings.subtitles&&p.hls.subtitleTracks.length?0:-1;p.hls.subtitleTrack=Number(subtitles.value);subtitles.onchange=()=>p.hls.subtitleTrack=Number(subtitles.value)});
 if(p.dash)p.dash.on(dashjs.MediaPlayer.events.STREAM_INITIALIZED,()=>{if(playback!==p)return;const q=element('select','',row);q.setAttribute('aria-label','Qualité vidéo');element('option','Automatique',q).value='auto';p.dash.getRepresentationsByType('video').forEach(r=>element('option',`${r.height||'?'}p`,q).value=r.id);q.onchange=()=>{p.dash.updateSettings({streaming:{abr:{autoSwitchBitrate:{video:q.value==='auto'}}}});if(q.value!=='auto')p.dash.setRepresentationForTypeById('video',q.value)};for(const [kind,label]of [['audio','Piste audio'],['text','Sous-titres']]){const tracks=p.dash.getTracksFor(kind);if(!tracks.length)continue;const select=element('select','',row);select.setAttribute('aria-label',label);if(kind==='text')element('option','Désactivés',select).value=-1;tracks.forEach((t,i)=>element('option',t.lang||t.labels?.[0]?.text||`Piste ${i+1}`,select).value=i);select.onchange=()=>{if(kind==='text')p.dash.enableText(Number(select.value)>=0);if(Number(select.value)>=0)p.dash.setCurrentTrack(tracks[Number(select.value)])};if(kind==='text'){const french=tracks.findIndex(t=>/^fr/i.test(t.lang||''));select.value=state.settings.subtitles?Math.max(0,french):-1;select.onchange()}}});
 for(const subtitle of media.subtitles||source.subtitles||[]){const track=element('track','',video);track.kind='subtitles';track.label=subtitle.label||subtitle.language||'Français';track.srclang=subtitle.language||'fr';track.src=subtitle.url;track.default=state.settings.subtitles;}
 api.segments(item.imdbId,episode?.season||episode?.seasonNumber||0,episode?.number||0,item.tag==='Film').then(value=>{if(playback===p)p.segments=value}).catch(()=>{});
 video.ondblclick=event=>{const r=video.getBoundingClientRect();seek(event.clientX-r.left<r.width/2?-15:15)};video.onended=()=>{if(state.settings.autoplay&&p.next)start(item,p.next,undefined,true);else savePosition()};
 p.tick=setInterval(()=>{if(playback!==p)return;const now=Date.now();if(now-p.savedAt>=3000){p.savedAt=now;savePosition();api.snapshot({title:item.title,position:video.currentTime*1000,duration:Number.isFinite(video.duration)?video.duration*1000:0,playing:!video.paused,anime:item,episode,hasPrevious:!!p.previous,hasNext:!!p.next})}skip.hidden=!Object.values(p.segments||{}).some(s=>s&&video.currentTime*1000>=s.start&&video.currentTime*1000<s.end&&s.start<video.duration*1000);
   if(deadline&&now>=deadline){video.pause();deadline=0;error.textContent='Minuteur terminé';button('Reprendre 3 h',row,()=>{deadline=Date.now()+180*60000;video.play();error.textContent=''})}dimmed=!!state.settings.pauseDimming&&video.paused&&now-lastInteraction>=30000;content.classList.toggle('dimmed',dimmed);
 },250);
 if(navigator.mediaSession){navigator.mediaSession.metadata=new MediaMetadata({title:item.title,artist:episode?.title||'TvSama'});for(const [action,fn]of [['play',()=>video.play()],['pause',()=>video.pause()],['seekbackward',()=>seek(-15)],['seekforward',()=>seek(15)]]){try{navigator.mediaSession.setActionHandler(action,fn)}catch{}}}
 row.querySelector('button')?.focus();
}
for(const name of pages)button(name,document.querySelector('nav'),()=>navigate(name));document.querySelector('#searchButton').onclick=()=>navigate('Recherche');document.querySelector('#cancel').onclick=()=>document.querySelector('#add').close();
document.querySelector('#streamForm').onsubmit=event=>{event.preventDefault();try{const url=new URL(document.querySelector('#url').value);if(url.protocol!=='https:'||url.username||url.password)throw Error('URL HTTPS sans identifiants requise');state.items.push({id:crypto.randomUUID(),title:document.querySelector('#title').value.trim(),url:url.href,provider:'Personnel',tag:'Film',episodes:[],favorite:false});persist();document.querySelector('#add').close();event.target.reset();render()}catch(e){document.querySelector('#formError').textContent=e.message}};
for(const type of ['pointerdown','pointermove','keydown'])document.addEventListener(type,event=>{lastInteraction=Date.now();if(dimmed){dimmed=false;content.classList.remove('dimmed');if(type!=='pointermove'){event.preventDefault();event.stopImmediatePropagation()}}},true);
document.addEventListener('keydown',event=>{if(event.defaultPrevented)return;if(event.key==='Escape'&&document.fullscreenElement){event.preventDefault();document.exitFullscreen().catch(e=>message(e.message));return}if(event.key==='Escape'&&!document.querySelector('dialog[open]')){navigate(page);return}if(event.target.matches('input,select,textarea'))return;if(playback&&event.key===' '&&!event.target.matches('button')){event.preventDefault();playback.video.paused?playback.video.play():playback.video.pause();return}if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key))return;if(playback&&event.target===playback.video&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const increment=core.seekIncrement(event.repeat?(Date.now()-(playback.seekStart||Date.now())):0);if(!event.repeat)playback.seekStart=Date.now();playback.video.currentTime=Math.max(0,playback.video.currentTime+(event.key==='ArrowLeft'?-1:1)*increment/1000);return}
 const root=document.querySelector('dialog[open]')||document,nodes=[...root.querySelectorAll('button,input,select,video')].filter(n=>!n.disabled&&!n.hidden&&n.getClientRects().length),active=document.activeElement;if(!nodes.includes(active)){nodes[0]?.focus();event.preventDefault();return}const r=active.getBoundingClientRect(),horizontal=/Left|Right/.test(event.key),sign=/Left|Up/.test(event.key)?-1:1;const targets=nodes.filter(n=>n!==active).map(n=>{const b=n.getBoundingClientRect(),dx=b.x+b.width/2-r.x-r.width/2,dy=b.y+b.height/2-r.y-r.height/2;return{n,d:(horizontal?dx:dy)*sign,c:Math.abs(horizontal?dy:dx)}}).filter(x=>x.d>1).sort((a,b)=>(a.d+a.c*3)-(b.d+b.c*3));targets[0]?.n.focus();document.activeElement.scrollIntoView({block:'nearest'});event.preventDefault();});
window.addEventListener('beforeunload',()=>{savePosition();clearTimeout(saveTimer);api.save(state)});
api.onClosing(async()=>{try{savePosition();clearTimeout(saveTimer);await api.save(state);await api.closeReady()}catch(e){message(`Fermez après avoir sauvegardé : ${e.message}`)}});
async function bootstrap(){try{const data=await api.bootstrap();state=core.migrate(data.state);const legacy=localStorage.getItem('tvsama-library');if(legacy&&!state.items.length&&!state.history.length){state=core.migrate(JSON.parse(legacy));await api.save(state);localStorage.removeItem('tvsama-library')}page=pages.includes(state.settings.startup)?state.settings.startup:'Accueil';api.onCommand(command=>{if(command.action==='search'){query=command.query||'';navigate('Recherche')}else if(command.action==='play'&&command.anime)start(command.anime,command.episode,command.sources);else if(command.action==='toggle'&&playback)playback.video.paused?playback.video.play():playback.video.pause();else if(command.action==='seek'&&playback)playback.video.currentTime=command.position/1000;else if(command.action==='previous'&&playback?.previous)start(playback.item,playback.previous,undefined,true);else if(command.action==='next'&&playback?.next)start(playback.item,playback.next,undefined,true);else if(command.action==='sleep'&&playback){deadline=Date.now()+180*60000;playback.video.play()}});await render();if(data.warning)message(data.warning)}catch(e){message(`Initialisation impossible : ${e.message}`)}}
bootstrap();
