const {test}=require('node:test');const assert=require('node:assert/strict');const core=require('./core/library.js');const {SourceMaintenance,DAY,HOUR}=require('./services/maintenance.cjs');const {Media}=require('./services/media.cjs');const {Providers}=require('./services/providers.cjs');
test('MyFluneo : décoder Flight sans mélanger les épisodes ni exécuter les scripts',()=>{const {fluneoServers}=require('./services/fluneo.cjs');const data={episode:{season_number:2,episode_number:3,url:'https://cdn.example/main',embeds_json:JSON.stringify({VOE:'https://voe.example/e/selected',unsafe:'javascript:alert(1)'})},next:{episode:{season_number:2,episode_number:4,url:'https://cdn.example/wrong'}}};const flight='a:'+JSON.stringify(data)+'\n';const text='<script>self.__next_f.push('+JSON.stringify([1,flight.slice(0,40)])+')</script><script>self.__next_f.push('+JSON.stringify([1,flight.slice(40)])+')</script><script>throw Error("must not execute")</script>';const result=fluneoServers(text,{season:2,number:3});assert.deepEqual(result.map(x=>x.url),['https://cdn.example/main','https://voe.example/e/selected']);});
test('Extraction sans extension : reconnaître le média et interrompre son téléchargement',async()=>{const {Network}=require('./services/network.cjs');let canceled=false;const body=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(16))},cancel(){canceled=true}});const p=new Providers(new Network(async()=>new Response(body,{headers:{'content-type':'video/mp4'}})),{state:core.fresh()});const [source]=await p.extract({url:'https://example.org/signed-token'});assert.equal(source.format,'mp4');assert.equal(canceled,true);});
function fixture(directory){const store={state:core.fresh(),save:async state=>{store.state=structuredClone(state)}};const network={cache:new Map([['old','cached']])};const providers={definitions:()=>[{name:'Source',kind:'html',defaultBase:'https://old.example/',base:store.state.addresses.Source||'https://old.example/'}],directory};let now=DAY*2;return {store,network,providers,maintenance:new SourceMaintenance(providers,network,store,{now:()=>now}),advance:time=>now+=time};}
test('Adresses : rafraîchissement automatique partagé, TTL et favoris migrés',async()=>{let calls=0;const f=fixture(async()=>{calls++;return [{name:'Source',url:'https://new.example/home',status:'active'}]});const result=await Promise.all([f.maintenance.refresh(),f.maintenance.refresh()]);assert.equal(calls,1);assert.equal(f.store.state.addresses.Source,'https://new.example/');assert.deepEqual(result[0].changed,['Source']);assert.equal(f.network.cache.size,0);assert.equal(f.maintenance.translate({provider:'Source',id:'https://old.example/series/test#episode=1'}).id,'https://new.example/series/test#episode=1');await f.maintenance.refresh();assert.equal(calls,1);f.advance(DAY+1);await f.maintenance.refresh();assert.equal(calls,2);});
test('Annuaire en panne : conserver les adresses et limiter les tentatives',async()=>{let calls=0;const f=fixture(async()=>{calls++;throw Error('Hors ligne')});f.store.state.addresses.Source='https://known.example/';assert.equal((await f.maintenance.refresh()).error,'Hors ligne');await f.maintenance.refresh({force:true});assert.equal(calls,1);assert.equal(f.store.state.addresses.Source,'https://known.example/');f.advance(HOUR+1);await f.maintenance.refresh({force:true});assert.equal(calls,2);});
test('Annuaire : rejeter HTTP, identifiants et sources non actives',async()=>{for(const entry of [{url:'http://evil.example/',status:'active'},{url:'https://user:secret@evil.example/',status:'active'},{url:'https://evil.example/',status:'blocked'}]){const f=fixture(async()=>[{name:'Source',...entry}]);await f.maintenance.refresh();assert.deepEqual(f.store.state.addresses,{});}});
test('Résolution : renouveler les lecteurs expirés et retrouver le même épisode',async()=>{const f=fixture(async()=>[]);let attempts=0;f.providers.details=async item=>({...item,episodes:[{id:'new',season:2,number:3,language:'VF'}]});f.providers.resolve=async(_item,episode)=>{if(++attempts===1)throw Error('URL expirée');assert.equal(episode.id,'new');return [{url:'https://cdn.example/fresh.mp4'}]};assert.equal((await f.maintenance.resolve({id:'show',provider:'Source'},{id:'old',season:2,number:3,language:'VF'}))[0].url,'https://cdn.example/fresh.mp4');assert.equal(attempts,2);});
test('Annulation : quitter une fiche sans attendre l’annuaire partagé',async()=>{let finish;const f=fixture(()=>new Promise(resolve=>finish=resolve));f.providers.details=async()=>{throw Error('HTTP 404')};const controller=new AbortController(),operation=f.maintenance.details({provider:'Source',id:'https://old.example/a'},controller.signal);await new Promise(r=>setImmediate(r));controller.abort(Error('Annulé'));await assert.rejects(operation,/Annulé/);finish([]);await f.maintenance.pending;});
test('Flux sans extension : détecter HLS par type MIME avant le lecteur',async()=>{const media=new Media(async()=>new Response('#EXTM3U\npart.ts',{headers:{'content-type':'application/vnd.apple.mpegurl'}}));const source=await media.prepare({url:'https://example.org/stream?id=1'});assert.equal(source.format,'hls');assert.equal(media.register(source).format,'hls');});
test('Film HTML : résolution vidéo sans épisode artificiel',async()=>{const p=new Providers({request:async()=>({text:'<video src="https://cdn.example/movie.mp4"></video>',url:'https://example.org/film'})},{state:core.fresh()});const sources=await p.resolve({id:'https://example.org/film',title:'Film',tag:'Film',provider:'Anime-Sama'});assert.equal(sources[0].url,'https://cdn.example/movie.mp4');});
