const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');const core=require('./core/library.js');
const movie={id:'movie',title:'Film personnel',provider:'Personnel',tag:'Film',url:'https://example.org/movie.mp4',episodes:[],favorite:false};
const series={id:'series',title:'Série uniquement VOSTFR',provider:'fixture',tag:'Série',episodes:[{id:'e1',title:'Épisode 1',season:1,number:1,language:'VOSTFR'},{id:'e2',title:'Épisode 2',season:1,number:2,language:'VOSTFR'}]};
const settle=()=>new Promise(resolve=>setTimeout(resolve,15));
async function fixture(t,{state=core.fresh(),details,media}={}){const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),{url:'https://desktop.invalid/',runScripts:'outside-only',pretendToBeVisual:true});t.after(()=>dom.window.close());const w=dom.window;w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLMediaElement.prototype.load=()=>{};w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.play=async()=>{};let command,detailsCalls=0;const api={bootstrap:async()=>({state:structuredClone(state)}),save:async()=>{},cancel:async()=>{},catalog:async()=>({items:[],sources:[]}),sources:async()=>[],details:async item=>{detailsCalls++;return details?details(item,detailsCalls):structuredClone(item)},resolve:async()=>[{url:'https://example.org/a.mp4',name:'A'},{url:'https://example.org/b.mp4',name:'B'}],media:media|| (async source=>({token:source.name,url:source.url})),releaseMedia:async()=>{},segments:async()=>null,snapshot:async()=>{},onCommand:cb=>{const previous=command;command=data=>{previous?.(data);cb(data)}},onCatalog:()=>{},onClosing:()=>{}};w.desktop=api;for(const file of ['core/library.js','controls.js','app.js'])w.eval(fs.readFileSync(path.join(__dirname,file),'utf8'));await settle();const click=async text=>{const button=text===''?w.document.querySelector('.card'):[...w.document.querySelectorAll('button')].find(n=>n.textContent===text);assert.ok(button,`Bouton absent : ${text}`);button.click();await settle();};return {w,click,command:data=>command(data),detailsCalls:()=>detailsCalls};}
test('La catégorie active suit son bouton',async t=>{const {w,click}=await fixture(t);await click('Films');assert.equal([...w.document.querySelectorAll('button')].find(n=>n.textContent==='Films').getAttribute('aria-pressed'),'true');});
test('Lecteurs expirés : renouvellement automatique unique puis erreur récupérable',async t=>{const f=await fixture(t);let calls=0;f.w.desktop.resolve=async(_item,_episode,options)=>{calls++;assert.equal(options.refresh,true);return [{url:'https://example.org/fresh.mp4',name:'Fresh'}]};f.command({action:'play',anime:series,episode:series.episodes[0],sources:[{url:'https://example.org/expired.mp4',name:'Old'}]});await settle();f.w.document.querySelector('video').dispatchEvent(new f.w.Event('error'));await settle();assert.equal(calls,1);assert.match(f.w.document.querySelector('video').src,/fresh/);f.w.document.querySelector('video').dispatchEvent(new f.w.Event('error'));await settle();assert.equal(calls,1);assert.ok([...f.w.document.querySelectorAll('button')].some(n=>n.textContent==='Renouveler les serveurs'&&!n.hidden));});
test('La recherche filtre aussi les flux personnels',async t=>{const state=core.fresh();state.items=[movie,{...movie,id:'other',title:'Autre titre'}];const f=await fixture(t,{state});await f.click('Recherche');const input=f.w.document.querySelector('input[type=search]');input.value='personnel';input.dispatchEvent(new f.w.Event('input'));await new Promise(r=>setTimeout(r,350));assert.equal(f.w.document.querySelectorAll('.card').length,1);});
test('Tous les favoris restent accessibles au-delà de 120 titres',async t=>{const state=core.fresh();state.settings.startup='Ma liste';state.items=Array.from({length:121},(_,i)=>({...movie,id:String(i),title:`Titre ${i}`,favorite:true}));const f=await fixture(t,{state});await f.click('Page suivante');assert.match(f.w.document.querySelector('.card').textContent,/Titre 120/);});
test('Retour du lecteur : fiche en cache sans nouvelle dépendance réseau',async t=>{const state=core.fresh();state.items=[movie];const f=await fixture(t,{state,details:(item,count)=>{if(count>1)throw Error('Hors ligne');return item}});await f.click('');await f.click('Lire / Reprendre');await f.click('Retour');assert.ok([...f.w.document.querySelectorAll('button')].some(n=>n.textContent==='Lire / Reprendre'));assert.equal(f.detailsCalls(),1);});
test('Échap en plein écran quitte le plein écran et conserve la lecture',async t=>{const state=core.fresh();state.items=[movie];const f=await fixture(t,{state});await f.click('');await f.click('Lire / Reprendre');let exited=false;Object.defineProperty(f.w.document,'fullscreenElement',{value:f.w.document.querySelector('video'),configurable:true});f.w.document.exitFullscreen=async()=>{exited=true};f.w.document.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await settle();assert.equal(exited,true);assert.ok(f.w.document.querySelector('video'));});
test('Ajouter un favori conserve la fiche même si la source tombe ensuite',async t=>{const state=core.fresh();state.items=[movie];const f=await fixture(t,{state,details:(item,count)=>{if(count>1)throw Error('Source hors ligne');return item}});await f.click('');await f.click('Ajouter à ma liste');assert.ok([...f.w.document.querySelectorAll('button')].some(n=>n.textContent==='Retirer de ma liste'));assert.equal(f.detailsCalls(),1);});
test('Un film ne présente pas un menu Saison vide',async t=>{const state=core.fresh();state.items=[movie];const f=await fixture(t,{state});await f.click('');assert.equal(f.w.document.querySelector('[aria-label="Saison"]'),null);});
test('Une série VOSTFR reste navigable quand la préférence est VF',async t=>{const state=core.fresh();state.items=[{...series,favorite:true}];state.settings.startup='Ma liste';const f=await fixture(t,{state});await f.click('');assert.equal(f.w.document.querySelectorAll('.episodes button').length,2);});
test('Un changement rapide de serveur ne remet pas le serveur précédent',async t=>{const state=core.fresh();state.items=[movie];let first=true;const f=await fixture(t,{state,media:async source=>{if(source.name==='A'&&!first)await new Promise(r=>setTimeout(r,70));first=false;return {token:source.name,url:source.url}}});await f.click('');await f.click('Lire / Reprendre');const control=f.w.document.querySelector('[aria-label="Serveur"]');control.value='0';control.dispatchEvent(new f.w.Event('change'));await settle();const second=f.w.document.querySelector('[aria-label="Serveur"]')||control;second.value='1';second.dispatchEvent(new f.w.Event('change'));await new Promise(r=>setTimeout(r,100));assert.match(f.w.document.querySelector('video').src,/b\.mp4$/);});
