const {Bonjour}=require('bonjour-service');const tls=require('node:tls');const {privateIPv4}=require('./remote.cjs');
const NS='urn:x-cast:com.google.cast.';
function varint(value){const out=[];do{out.push((value&127)|(value>127?128:0));value=Math.floor(value/128)}while(value);return Buffer.from(out)}
function encodeMessage(namespace,destination,payload){const text=(field,value)=>{const bytes=Buffer.from(value);return Buffer.concat([varint(field*8+2),varint(bytes.length),bytes])};const body=Buffer.concat([Buffer.from([8,0]),text(2,'sender-tvsama'),text(3,destination),text(4,namespace),Buffer.from([40,0]),text(6,JSON.stringify(payload))]);const head=Buffer.alloc(4);head.writeUInt32BE(body.length);return Buffer.concat([head,body])}
function decodeMessage(body){let offset=0;const fields={};function read(){let value=0,mult=1;for(let n=0;n<5;n++){if(offset>=body.length)throw Error('Cast tronqué');const b=body[offset++];value+=(b&127)*mult;if(!(b&128))return value;mult*=128}throw Error('Cast varint invalide')}while(offset<body.length){const tag=read(),field=tag>>>3,wire=tag&7;if(wire===0)fields[field]=read();else if(wire===2){const length=read();if(length>body.length-offset)throw Error('Cast tronqué');fields[field]=body.subarray(offset,offset+length).toString();offset+=length}else throw Error('Type Cast invalide')}return {namespace:fields[4],payload:fields[6]?JSON.parse(fields[6]):{}}}
class Cast {
 constructor({connect=tls.connect}={}){this.connectTLS=connect;this.devices=new Map();this.pending=new Map();this.requestId=0;}
 discover(){if(!this.bonjour){this.bonjour=new Bonjour();this.browser=this.bonjour.find({type:'googlecast'},service=>{const host=service.addresses?.find(privateIPv4);if(host)this.devices.set(host,{host,name:service.txt?.fn||service.name})})}return [...this.devices.values()];}
 send(namespace,destination,payload){if(!this.socket||this.socket.destroyed)throw Error('Cast déconnecté');this.socket.write(encodeMessage(NS+namespace,destination,payload));}
 request(namespace,destination,payload){return new Promise((resolve,reject)=>{const requestId=++this.requestId;const timer=setTimeout(()=>{this.pending.delete(requestId);reject(Error('Délai Cast dépassé'))},10000);this.pending.set(requestId,{resolve,reject,timer});try{this.send(namespace,destination,{...payload,requestId})}catch(e){clearTimeout(timer);this.pending.delete(requestId);reject(e)}});}
 async connect(host,source,position=0){if(!privateIPv4(host))throw Error('Récepteur local requis');if(Object.keys(source.headers||{}).some(k=>k.toLowerCase()!=='user-agent'))throw Error('Ce flux exige des en-têtes incompatibles avec Cast');await this.closeClient();
  await new Promise((resolve,reject)=>{const socket=this.connectTLS({host,port:8009,rejectUnauthorized:false},resolve);this.socket=socket;this.socket.setTimeout(10000,()=>this.socket.destroy(Error('Récepteur Cast injoignable')));this.socket.once('error',reject);this.socket.on('error',()=>{if(this.socket===socket)this.closeClient()});this.socket.on('close',()=>{if(this.socket===socket)this.closeClient()});let bytes=Buffer.alloc(0);this.socket.on('data',chunk=>{if(this.socket!==socket)return;bytes=Buffer.concat([bytes,chunk]);if(bytes.length>1024*1024){this.closeClient();return}while(bytes.length>=4){const length=bytes.readUInt32BE();if(length>1024*1024){this.closeClient();return}if(bytes.length<length+4)break;const body=bytes.subarray(4,length+4);bytes=bytes.subarray(length+4);try{const message=decodeMessage(body);if(message.namespace===NS+'tp.heartbeat'&&message.payload.type==='PING')this.send('tp.heartbeat','receiver-0',{type:'PONG'});const pending=this.pending.get(message.payload.requestId);if(pending){clearTimeout(pending.timer);this.pending.delete(message.payload.requestId);/ERROR|FAILED/.test(message.payload.type)?pending.reject(Error(message.payload.reason||message.payload.type)):pending.resolve(message.payload)}}catch{this.closeClient();return}}});});
  this.socket.setTimeout(0);this.send('tp.connection','receiver-0',{type:'CONNECT'});this.heartbeat=setInterval(()=>{try{this.send('tp.heartbeat','receiver-0',{type:'PING'})}catch{this.closeClient()}},5000);this.heartbeat.unref();const launched=await this.request('receiver','receiver-0',{type:'LAUNCH',appId:'CC1AD845'});const app=launched.status?.applications?.find(a=>a.appId==='CC1AD845');if(!app)throw Error('Récepteur média indisponible');this.transport=app.transportId;this.send('tp.connection',this.transport,{type:'CONNECT'});
  const contentType=/\.m3u8(?:[?#]|$)/i.test(source.url)?'application/x-mpegURL':/\.mpd(?:[?#]|$)/i.test(source.url)?'application/dash+xml':'video/mp4';const loaded=await this.request('media',this.transport,{type:'LOAD',autoplay:true,currentTime:position/1000,media:{contentId:source.url,contentType,streamType:'BUFFERED',metadata:{metadataType:0,title:source.title||'TvSama'}}});this.sessionId=loaded.status?.[0]?.mediaSessionId;return loaded.status?.[0];
 }
 async command(action,position){if(!this.transport)throw Error('Aucun récepteur Cast');const types={status:'GET_STATUS',pause:'PAUSE',play:'PLAY',seek:'SEEK'};if(!types[action])throw Error('Commande Cast inconnue');const result=await this.request('media',this.transport,{type:types[action],mediaSessionId:this.sessionId,...(action==='seek'?{currentTime:position/1000}:{})});return result.status?.[0]||{};}
 async closeClient(){clearInterval(this.heartbeat);const socket=this.socket;this.socket=null;socket?.destroy();for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Cast déconnecté'))}this.pending.clear();this.transport=null;this.sessionId=null;}
 close(){this.closeClient();this.browser?.stop();this.bonjour?.destroy();}
}
module.exports={Cast,encodeMessage,decodeMessage};
