// Decode data only. Remote JavaScript is never evaluated in the main process.
function unescapeLiteral(text){return text.replace(/\\(x[0-9a-f]{2}|u[0-9a-f]{4}|[\s\S])/gi,(_m,c)=>c[0]==='x'||c[0]==='u'?String.fromCharCode(parseInt(c.slice(1),16)):({n:'\n',r:'\r',t:'\t'}[c]||c));}
function unpack(text){const result=[];const pattern=/\}\s*\(\s*(['"])((?:\\.|(?!\1)[\s\S])*?)\1\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(['"])((?:\\.|(?!\5)[\s\S])*?)\5\.split\(\s*['"]\|['"]\s*\)/g;for(const m of text.matchAll(pattern)){const radix=Number(m[3]),count=Number(m[4]);if(radix<2||radix>62||count>10000||m[2].length>2e6)continue;const dictionary=unescapeLiteral(m[6]).split('|'),alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';result.push(unescapeLiteral(m[2]).replace(/\b\w+\b/g,token=>{let value=0;for(const c of token){const digit=alphabet.indexOf(c);if(digit<0||digit>=radix)return token;value=value*radix+digit;if(value>=count)return token;}return dictionary[value]||token;}));}return result;}
function mediaCandidates(html){const texts=[html,...unpack(html)],urls=[];for(const text of texts){const normalized=text.replace(/\\\//g,'/').replace(/\\u0026/gi,'&').replace(/&amp;/g,'&');for(const m of normalized.matchAll(/["']([^"'<>\s]+\.(?:mp4|m3u8|mpd)(?:[?#][^"'<>\s]*)?)["']/gi))urls.push(m[1]);for(const m of normalized.matchAll(/(?:\bfile\b|\bsrc\b|\bsource\b|\bvideo_url\b)\s*["']?\s*[:=]\s*["']([^"']+)["']/gi))if(/\.(mp4|m3u8|mpd)(?:[?#]|$)/i.test(m[1]))urls.push(m[1]);}return [...new Set(urls)];}
function decodeVoe(value){if(typeof value!=='string'||value.length>1024*1024)return null;try{let text=value.replace(/[a-z]/gi,c=>String.fromCharCode(c.charCodeAt(0)+(c.toLowerCase()<='m'?13:-13))).replace(/@\$|\^\^|~@|%\?|\*~|!!|#&|_/g,'');text=Buffer.from(text,'base64').toString('utf8');text=[...text].map(c=>String.fromCharCode(c.charCodeAt(0)-3)).reverse().join('');const data=JSON.parse(Buffer.from(text,'base64').toString('utf8'));return typeof data.source==='string'?data:null;}catch{return null;}}
function streamtapeURL(text,base){const m=/document\.getElementById\(['"](?:botlink|robotlink)['"]\)\.innerHTML\s*=\s*['"]([^'"]+)['"]\s*\+\s*\(['"]([^'"]+)['"]\)\.substring\((\d+)\)/.exec(text);if(!m)return null;try{const url=new URL(m[1]+m[2].slice(Number(m[3])),base);if(url.protocol!=='https:'||!url.pathname.includes('get_video')||!url.searchParams.has('token'))return null;url.searchParams.set('stream','1');return url.href}catch{return null;}}
function literalRedirect(html){for(const text of [html,...unpack(html)]){const match=/(?:window\.)?location(?:\.href)?\s*(?:=\s*|\.replace\(\s*)["']([^"']+)["']/i.exec(text);if(match)return unescapeLiteral(match[1]);const refresh=/<meta[^>]*http-equiv=["']refresh["'][^>]*content=["'][^"']*url=([^"'>]+)/i.exec(text);if(refresh)return refresh[1].trim();}return null;}
function playerSources(html){const out=[];for(const text of [html,...unpack(html)]){for(const match of text.matchAll(/\b(?:file|video_url)\s*["']?\s*[:=]\s*(?:atob\(\s*(["'])([^"']+)\1\s*\)|(["'])([^"']+)\3)/gi)){const value=match[2]?Buffer.from(match[2],'base64').toString('utf8'):unescapeLiteral(match[4]);if(/^(?:https:\/\/|\/)/i.test(value)&&! /\.(?:vtt|srt|js|css|png|jpg)(?:[?#]|$)/i.test(value))out.push(value);}}return [...new Set(out)];}
module.exports={unpack,mediaCandidates,decodeVoe,streamtapeURL,literalRedirect,playerSources};
