const {load}=require('cheerio');const {DateTime}=require('luxon');
function parseEvents(text,url,now=Date.now()){const $=load(text);if(!$('tbody.events').length)throw Error('Calendrier absent ou validation requise');const result=[];const today=DateTime.fromMillis(now,{zone:'Europe/Paris'}).startOf('day');$('tbody.events tr.event').each((_i,n)=>{const row=$(n),link=row.find('a[href*="-streaming-direct"]').first(),title=row.find('.event-title,.home').first().text().trim(),clock=row.find('td.dt').text().trim(),dateText=row.find('td').eq(1).text().trim();if(!title||!/^\d{1,2}:\d{2}$/.test(clock)||!link.length)return;let date=/^(aujourd'hui|today)$/i.test(dateText)?today:/^(demain|tomorrow)$/i.test(dateText)?today.plus({days:1}):DateTime.fromFormat(dateText,'dd-LLL-yyyy',{locale:'en',zone:'Europe/Paris'});const[hour,minute]=clock.split(':').map(Number);date=date.set({hour,minute});if(!date.isValid)return;const address=new URL(link.attr('href'),url).href;result.push({id:link.attr('k')||address,title,competition:row.find('td').eq(3).text().trim(),startsAt:date.toMillis(),isLive:row.find('img[src]').toArray().some(i=>/\/live.gif$/i.test($(i).attr('src')))&&date.toMillis()<=now,url:address})});return [...new Map(result.map(e=>[e.id,e])).values()].sort((a,b)=>a.startsAt-b.startsAt);}
class Live {
 constructor(network,store,notify){this.network=network;this.store=store;this.notify=notify;this.interval=setInterval(()=>this.tick().catch(()=>{}),15000);this.interval.unref();}
 async events(signal){let error;for(const url of ['https://volkamax.club/','https://bzh.lat/']){try{const data=await this.network.request(url,{signal,ttl:60000});return parseEvents(data.text,data.url)}catch(e){error=e;if(signal?.aborted)throw e}}throw error;}
 async schedule(event){if(!event?.id||!Number.isFinite(event.startsAt)||event.startsAt-Date.now()<=600000)throw Error('Horaire au moins 10 minutes à l’avance requis');this.store.state.reminders||={};if(this.store.state.reminders[event.id])delete this.store.state.reminders[event.id];else this.store.state.reminders[event.id]={id:event.id,title:String(event.title).slice(0,250),startsAt:event.startsAt};await this.store.save(this.store.state);return this.store.state.reminders;}
 async tick(now=Date.now()){const reminders=this.store.state.reminders||{};let changed=false;for(const [id,e]of Object.entries(reminders)){if(e.startsAt-600000<=now){if(e.startsAt>now)this.notify(e.title);delete reminders[id];changed=true}}if(changed)await this.store.save(this.store.state);}
 close(){clearInterval(this.interval);}
}
module.exports={Live,parseEvents};
