const crypto=require('node:crypto');const zlib=require('node:zlib');const {PNG}=require('pngjs');const {httpsURL,UA}=require('./network.cjs');
const MAX=32*1024*1024;
async function manifestText(response,limit=8*1024*1024){const chunks=[];let size=0;for await(const chunk of response.body){size+=chunk.byteLength;if(size>limit)throw Error('Texte média trop volumineux');chunks.push(chunk)}return Buffer.concat(chunks).toString('utf8');}
function validTS(data){return data.length>=564&&data[0]===0x47&&data[188]===0x47&&data[376]===0x47;}
function unwrap(data){if(data.length>MAX)throw Error('Segment trop volumineux');let result;
 const raw=data.indexOf(Buffer.from('TIKTIKRAW')),gz=data.indexOf(Buffer.from('TIKTIKTSGZ'));
 if(raw>=0)result=data.subarray(raw+9);else if(gz>=0)result=zlib.gunzipSync(data.subarray(gz+10),{maxOutputLength:MAX});
 else if(data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))){if(data.length<33)throw Error('PNG tronqué');const width=data.readUInt32BE(16),height=data.readUInt32BE(20);if(width*height*4>MAX)throw Error('PNG trop volumineux');let offset=8;while(offset+12<=data.length){const len=data.readUInt32BE(offset);if(len>data.length-offset-12)throw Error('PNG tronqué');if(data.toString('ascii',offset+4,offset+8)==='IEND'){const tail=data.subarray(offset+12+len);if(validTS(tail)){result=tail;break}}offset+=12+len}
  if(!result){const png=PNG.sync.read(data),rgb=Buffer.alloc(png.width*png.height*3);for(let i=0,j=0;i<png.data.length;i+=4){rgb[j++]=png.data[i];rgb[j++]=png.data[i+1];rgb[j++]=png.data[i+2]}if(rgb.toString('ascii',0,8)!=='TIKTIKPX')throw Error('PNG sans segment vidéo');const length=rgb.readUInt32BE(8);if(length>rgb.length-12)throw Error('Pixels tronqués');result=zlib.gunzipSync(rgb.subarray(12,12+length),{maxOutputLength:MAX})}}
 else if(data.toString('ascii',0,4)==='RIFF'&&data.toString('ascii',8,12)==='WEBP'){let offset=12;while(offset+8<=data.length){const len=data.readUInt32LE(offset+4);if(len>data.length-offset-8)throw Error('WebP tronqué');if(data.toString('ascii',offset,offset+4)==='EXIF'){result=data.subarray(offset+8,offset+8+len);break}offset+=8+len+(len%2)}}
 else return data;if(!result||!validTS(result))throw Error('Enveloppe sans paquets MPEG-TS valides');return result;
}
function guardBody(response,controller,source,signal,idleTimeout){
 const finish=()=>{clearTimeout(timer);signal.removeEventListener('abort',abort);source.controllers.delete(controller);};
 if(!response.body){source.controllers.delete(controller);return response;}
 const reader=response.body.getReader();let timer,ended=false,stream;
 const abort=()=>{if(ended)return;ended=true;finish();stream.error(signal.reason||Error('Requête média annulée'));reader.cancel().catch(()=>{});};
 const body=new ReadableStream({start(value){stream=value;signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort();},async pull(value){if(ended)return;timer=setTimeout(()=>controller.abort(Error('Délai réseau dépassé')),idleTimeout);try{const part=await reader.read();clearTimeout(timer);if(ended)return;if(part.done){ended=true;finish();value.close();}else value.enqueue(part.value);}catch(error){if(!ended){ended=true;finish();value.error(error);}}},async cancel(){if(ended)return;ended=true;finish();controller.abort(Error('Requête média annulée'));await reader.cancel().catch(()=>{});}});
 return new Response(body,{status:response.status,statusText:response.statusText,headers:response.headers});
}
class Media {
 constructor(fetcher,{idleTimeout=15000}={}){this.fetcher=fetcher;this.idleTimeout=idleTimeout;this.sessions=new Map();}
 async prepare(source){if(source.format||/\.(mp4|m3u8|mpd)(?:[?#]|$)/i.test(source.url))return source;const request=new Request(source.url,{headers:{Range:'bytes=0-4095'}}),{response}=await this.upstream(source.url,{...source,origin:httpsURL(source.url).origin},request);try{if(!response.ok)throw Error(`HTTP ${response.status}`);const type=response.headers.get('content-type')||'';let format=/mpegurl/i.test(type)?'hls':/dash\+xml/i.test(type)?'dash':/video\/mp4/i.test(type)?'mp4':'';if(!format){const reader=response.body?.getReader();if(reader){const first=await reader.read();const text=new TextDecoder().decode(first.value?.subarray(0,4096));format=/^\s*#EXTM3U/.test(text)?'hls':/<MPD[\s>]/.test(text)?'dash':'';await reader.cancel();}}return {...source,format};}finally{if(!response.body?.locked)await response.body?.cancel().catch(()=>{});}}
 register(source){httpsURL(source.url);if(this.sessions.size>=4)this.remove(this.sessions.keys().next().value);const token=crypto.randomBytes(18).toString('hex');this.sessions.set(token,{...source,origin:new URL(source.url).origin,controllers:new Set()});return {token,url:this.url(token,source.url),format:source.format,subtitles:(source.subtitles||[]).map(s=>({...s,url:this.url(token,s.url)}))};}
 url(token,raw){const u=httpsURL(raw);return `tvsama-media://${token}/${u.host}${u.pathname}${u.search}`;}
 remove(token){const source=this.sessions.get(token);for(const controller of source?.controllers||[])controller.abort(Error('Session média fermée'));this.sessions.delete(token);}
 rewriteHLS(text,base,token){return text.split(/\r?\n/).map(line=>{if(line.startsWith('#'))return line.replace(/URI="([^"]+)"/g,(_m,uri)=>`URI="${this.url(token,new URL(uri,base).href)}"`);return line.trim()?this.url(token,new URL(line.trim(),base).href):line}).join('\n');}
 async upstream(raw,source,request){let target=httpsURL(raw);source.controllers||=new Set();for(let hop=0;hop<6;hop++){const headers={'User-Agent':UA,...source.headers};if(target.origin!==source.origin)for(const key of Object.keys(headers))if(!['user-agent','referer','origin'].includes(key.toLowerCase()))delete headers[key];if(request.headers.get('Range'))headers.Range=request.headers.get('Range');const controller=new AbortController(),signal=AbortSignal.any([request.signal,controller.signal]);source.controllers.add(controller);const timeout=setTimeout(()=>controller.abort(Error('Délai réseau dépassé')),this.idleTimeout);let response;try{response=await this.fetcher(target.href,{headers,signal,redirect:'manual'});}catch(error){source.controllers.delete(controller);throw error;}finally{clearTimeout(timeout)}if([301,302,303,307,308].includes(response.status)&&response.headers.get('location')){await response.body?.cancel();source.controllers.delete(controller);target=httpsURL(new URL(response.headers.get('location'),target));continue}return {response:guardBody(response,controller,source,signal,this.idleTimeout),target};}throw Error('Trop de redirections vidéo');}
 async handle(request){const input=new URL(request.url),source=this.sessions.get(input.hostname);if(!source)return new Response('Session expirée',{status:410});const slash=input.pathname.indexOf('/',1),host=slash<0?input.pathname.slice(1):input.pathname.slice(1,slash),path=slash<0?'/':input.pathname.slice(slash);const {response,target}=await this.upstream(`https://${host}${path}${input.search}`,source,request);if(!response.ok){await response.body?.cancel();throw Error('HTTP '+response.status+' ('+target.hostname+')');}const output=new Headers(response.headers);output.set('Access-Control-Allow-Origin','*');output.delete('Content-Security-Policy');output.delete('Set-Cookie');output.delete('Content-Encoding');
  const type=output.get('content-type')||'';if(response.ok&&(/\.(srt|vtt)$/i.test(target.pathname)||/subrip|text\/vtt/i.test(type))){let text=await manifestText(response,2*1024*1024);if(!text.trimStart().startsWith('WEBVTT'))text='WEBVTT\n\n'+text.replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g,'$1.$2');output.delete('content-length');output.set('content-type','text/vtt; charset=utf-8');return new Response(text,{status:response.status,headers:output})}if(response.ok&&(/\.m3u8$/i.test(target.pathname)||/mpegurl/i.test(type))){const text=await manifestText(response);if(text.length>8*1024*1024)throw Error('Manifeste trop volumineux');output.delete('content-length');output.set('content-type','application/vnd.apple.mpegurl');return new Response(this.rewriteHLS(text,response.url||target.href,input.hostname),{status:response.status,headers:output})}
  if(response.ok&&(/\.mpd$/i.test(target.pathname)||/dash\+xml/i.test(type))){const text=await manifestText(response);if(text.length>8*1024*1024)throw Error('Manifeste trop volumineux');const base=response.url||target.href;const rewritten=text.replace(/<BaseURL([^>]*)>([^<]+)<\/BaseURL>/g,(_m,attr,value)=>`<BaseURL${attr}>${this.url(input.hostname,new URL(value,base).href).replaceAll('&','&amp;')}</BaseURL>`).replace(/(media|initialization|sourceURL)="(https:[^"]+)"/g,(_m,attr,value)=>`${attr}="${this.url(input.hostname,value.replaceAll('&amp;','&')).replaceAll('&','&amp;')}"`);output.delete('content-length');output.set('content-type','application/dash+xml');return new Response(rewritten,{status:response.status,headers:output})}
  if(response.ok&&/\.(ts|png|webp|jpg)$/i.test(target.pathname)){const chunks=[];let size=0;for await(const chunk of response.body){size+=chunk.length;if(size>MAX)throw Error('Segment trop volumineux');chunks.push(chunk)}const decoded=unwrap(Buffer.concat(chunks));output.set('content-type','video/mp2t');output.set('content-length',String(decoded.length));return new Response(decoded,{status:response.status,headers:output})}
  return new Response(response.body,{status:response.status,headers:output});
 }
}
module.exports={Media,unwrap,validTS};
