const {load}=require('cheerio');
const core=require('../core/library.js');
const {httpsURL}=require('./network.cjs');
const {chapterFrames}=require('./chapter-frames.cjs');
const {fluneoServers}=require('./fluneo.cjs');
const {resolveServers}=require('./server-pool.cjs');
const {mediaCandidates,decodeVoe,streamtapeURL,literalRedirect,playerSources}=require('./extraction.cjs');
const DEFINITIONS=[
 {name:'Anime-Sama',base:'https://anime-sama.to/',kind:'sama',animation:true},
 {name:'Voiranime',base:'https://voir-anime.to/',kind:'madara',animation:true},
 {name:'AnimeKO',base:'https://v4.animeko.ws/',kind:'ko',animation:true},
 {name:'MyFluneo',base:'https://myfluneo.eu/',kind:'fluneo',animation:true},
 {name:'Pluto TV FR',base:'https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/main/playlists/plutotv_fr.m3u',kind:'m3u',live:true},
 {name:'IPTV-Org FR',base:'https://iptv-org.github.io/iptv/languages/fra.m3u',kind:'m3u',live:true},
];
const pending=['FrAnime','FrenchStreaming','WarFlix','Coflix','BlablaStream','AnimeUltime','AnimesSama','PapaduStream','Movix','Wiflix','FrenchAnime','FrenchStream','Frembed','FrenchManga','Vavoo FR'];
const absolute=(raw,base)=>{if(typeof raw!=='string'||!raw.trim())return '';try{return httpsURL(new URL(raw,base)).href}catch{return ''}};
function parseM3U(text,provider){const items=[];let meta;for(const line of text.split(/\r?\n/)){const value=line.trim();if(value.startsWith('#EXTINF')){const attr=name=>new RegExp(`${name}="([^"]*)"`).exec(value)?.[1]||'';meta={title:value.slice(value.indexOf(',')+1).trim(),poster:attr('tvg-logo'),group:attr('group-title'),headers:{}};if(attr('http-user-agent'))meta.headers['User-Agent']=attr('http-user-agent');if(attr('http-referrer'))meta.headers.Referer=attr('http-referrer');}else if(meta&&value.startsWith('#EXTVLCOPT:')){const [,key,...rest]=value.match(/^#EXTVLCOPT:([^=]+)=(.*)$/)||[];if(key==='http-user-agent')meta.headers['User-Agent']=rest.join('=');if(key==='http-referrer')meta.headers.Referer=rest.join('=');}else if(meta&&/^https:\/\//.test(value)){items.push({...meta,id:value,url:value,provider,tag:'Direct',episodes:[]});meta=null}}return items;}
function parseCards(text,url,provider){const $=load(text),items=[];const selector=provider.kind==='sama'?'.catalog-card':provider.kind==='madara'?'.page-item-detail, .c-tabs-item__content':provider.kind==='ko'?'a[href*="/anime/"]':'a[href*="/anime/"]';
 $(selector).each((_i,node)=>{const card=$(node),link=card.is('a')?card:card.find('a[href]').first();const id=absolute(link.attr('href'),url);if(!id||id.includes('/episode-'))return;const img=card.find('img').first();const title=card.find('h2,h3,.post-title,.short_title').first().text().trim()||link.attr('title')||img.attr('alt')||link.attr('aria-label');if(!title)return;const poster=absolute(img.attr('data-src')||img.attr('data-lazy-src')||img.attr('src')||'',url);items.push({id,title,poster,provider:provider.name,tag:'Série',episodes:[]})});return [...new Map(items.map(x=>[x.id,x])).values()];}
function samaPlayers(script){return [...script.matchAll(/(?:var|let|const)\s+eps\d+\s*=\s*\[([\s\S]*?)]/g)].map(match=>[...match[1].matchAll(/["']([^"']*)["']/g)].map(x=>x[1].replace(/\\\//g,'/')));}
function samaSeasons(text,url){const code=text.replace(/\/\*[\s\S]*?\*\//g,'');return [...code.matchAll(/panneauAnime\(\s*["']([^"']+)["']\s*,\s*["']([^"']+)["']\s*\)/g)].filter(x=>/\/(vf|vostfr)\/?$/.test(x[2])&&!/live[- ]?action/i.test(x[1])).map((x,i)=>({id:absolute(`${x[2].replace(/\/$/,'')}/`,`${url.replace(/\/$/,'')}/`),title:x[1],number:Number(/saison(\d+)/.exec(x[2])?.[1]||i+1),language:x[2].split('/').filter(Boolean).at(-1).toUpperCase()}));}
class Providers {
 constructor(network,store){this.network=network;this.store=store;this.status={};}
 definitions(){return DEFINITIONS.map(p=>({...p,defaultBase:p.base,base:this.store.state.addresses[p.name]||p.base}));}
 list(){return [...this.definitions().map(p=>({...p,ported:true,enabled:!this.store.state.disabled.includes(p.name),status:this.status[p.name]||'Non vérifié'})),...pending.filter(name=>!this.definitions().some(p=>core.normalize(p.name)===core.normalize(name))).map(name=>({name,ported:false,enabled:false,status:'Adaptateur non porté'}))];}
 async catalog({query='',category='Tous',page=1,requestToken},signal){const providers=this.definitions().filter(p=>['sama','madara','ko','fluneo','m3u'].includes(p.kind)).filter(p=>!this.store.state.disabled.includes(p.name)&&(category==='TV en direct'?p.live:!p.live)&&(category!=='Animation'||p.animation)&&category!=='Films');const found=[];
  await Promise.all(providers.map(async p=>{try{let address=p.base;if(p.kind==='m3u'){const data=await this.network.request(address,{signal,ttl:1800000});const items=parseM3U(data.text,p.name).filter(x=>core.normalize(x.title).includes(core.normalize(query))).slice((page-1)*60,page*60);found.push(...items);this.publish?.(items,{query,category,page,requestToken},signal);}
   else {const q=encodeURIComponent(query);if(p.kind==='sama')address+=`catalogue/?search=${q}&type%5B%5D=Anime&page=${page}`;else if(p.kind==='madara')address+=query?`?s=${q}&post_type=wp-manga&paged=${page}`:`page/${page}/`;else if(p.kind==='ko')address+=`animes?q=${q}&page=${page}`;else address+=`catalog?q=${q}&page=${page}`;const data=await this.network.request(address,{signal});if(p.kind==='fluneo'&&!parseCards(data.text,data.url,p).length){const api=new URL('api/animes',p.base);api.search=new URLSearchParams({q:query,page:String(page),pageSize:'36'});const body=await this.network.request(api.href,{signal,json:true,headers:{Referer:address}});const items=(Array.isArray(body)?body:body.items||[]).filter(x=>x.slug&&x.title).map(x=>({id:new URL('anime/'+x.slug,p.base).href,title:x.title,poster:absolute(x.thumbnail,p.base),provider:p.name,tag:x.type==='movie'?'Film':'Série',episodes:[]}));found.push(...items);this.publish?.(items,{query,category,page,requestToken},signal);this.status[p.name]=items.length?'Catalogue disponible':'Aucun résultat';return;}if(/Just a moment|cf-chl-|captcha-platform/i.test(data.text))throw Error('Validation de sécurité requise');const items=parseCards(data.text,data.url,p);if(!items.length)throw Error('Aucun résultat ou structure non reconnue');found.push(...items);this.publish?.(items,{query,category,page,requestToken},signal);}
   this.status[p.name]='Catalogue disponible';}catch(e){if(signal?.aborted)throw e;this.status[p.name]=e.message;}}));return {items:core.mergeCatalog(found),sources:this.list()};
 }
 async details(item,signal){if(item.url)return item;const provider=this.definitions().find(p=>p.name===item.provider);if(!provider)throw Error('Adaptateur non porté');const data=await this.network.request(item.id,{signal}),$=load(data.text);const result={...item,title:$('h1').first().text().trim()||item.title,description:$('#synopsisText,.summary__content').first().text().trim()||$('meta[name=description]').attr('content')||'',poster:item.poster||absolute($('meta[property="og:image"]').attr('content')||'',data.url),episodes:[]};
  if(provider.kind==='sama'){const seasons=samaSeasons(data.text,data.url);for(const season of seasons){const scripts=await this.network.request(new URL('episodes.js',season.id).href,{signal});const players=samaPlayers(scripts.text),count=Math.max(0,...players.map(x=>x.length));for(let i=0;i<count;i++)result.episodes.push({id:`${season.id}#episode=${i}`,title:`Épisode ${i+1} ${season.language}`,season:season.number,number:i+1,language:season.language,sources:players.map((list,n)=>({url:absolute(list[i]||'',season.id),name:`Serveur ${n+1}`,language:season.language})).filter(x=>x.url)})}}
  else if(provider.kind==='ko'){$('tr[data-watch-url]').each((_i,n)=>{const row=$(n),number=Number(row.find('.episode-num-badge').text());if(number)result.episodes.push({id:absolute(row.attr('data-watch-url'),data.url),number,season:1,language:'VOSTFR',title:`Épisode ${number}`})})}
  else {$(provider.kind==='madara'?'.wp-manga-chapter a':'a[href*="/saison-"][href*="/episode-"]').each((_i,n)=>{const link=$(n),id=absolute(link.attr('href'),data.url),number=Number(/(?:episode-|-(\d+)-(?:vf|vostfr))/.test(id)?(/episode-(\d+)/.exec(id)||/-(\d+)-(?:vf|vostfr)/.exec(id))?.[1]:0);if(number)result.episodes.push({id,title:link.text().trim()||`Épisode ${number}`,number,season:Number(/saison-(\d+)/.exec(id)?.[1]||1),language:/vostfr/i.test(id)?'VOSTFR':/\bvf\b/i.test(id)?'VF':'UNKNOWN'})})}
  result.episodes=[...new Map(result.episodes.map(x=>[x.id,x])).values()].sort((a,b)=>a.season-b.season||a.number-b.number);return result;
 }
 async resolve(item,episode,signal){if(item.url)return [{url:item.url,name:item.provider||'Personnel',headers:item.headers||{},language:item.language||'UNKNOWN'}];let entries=episode?.sources||[];
  if(!entries.length){const address=episode?.id||(item.tag==='Film'||item.tag==='Direct'?item.id:null);if(!address)throw Error('Aucun épisode disponible');const data=await this.network.request(address,{signal}),$=load(data.text);if($('#player-captcha-overlay').length)throw Error('Captcha requis : ouvrez l’accès au site dans Sources, validez puis réessayez.');if(item.provider==='Voiranime')entries.push(...chapterFrames(data.text,data.url));if(item.provider==='MyFluneo')entries.push(...fluneoServers(data.text,episode));$('iframe[src],iframe[data-src],video source[src],video[src]').each((_i,n)=>{const node=$(n),url=absolute(node.attr('src')||node.attr('data-src'),data.url);if(url)entries.push({url,name:new URL(url).hostname,language:episode?.language})});}
  return resolveServers(entries,(entry,task)=>this.extract(entry,task),signal).catch(error=>{this.status[item.provider]=error.message;throw error});
 }
 async extract(entry,signal,depth=0,visited=new Set()){httpsURL(entry.url);const entryURL=new URL(entry.url);if(['vidara.to','vidara.so'].includes(entryURL.hostname)){const filecode=entryURL.pathname.split('/').filter(Boolean).at(-1);if(!filecode)throw Error('Identifiant Vidara absent');const data=await this.network.request(new URL('/api/stream',entryURL).href,{signal,json:true,method:'POST',body:JSON.stringify({filecode,device:'web'}),headers:{'Content-Type':'application/json',Referer:entry.url}});const url=absolute(data.streaming_url,entry.url);if(!url)throw Error('Vidara : aucun média publié');return [{...entry,url,subtitles:(data.subtitles||[]).map(s=>({url:absolute(s.file_path,entry.url),label:s.language,language:s.language})).filter(s=>s.url)}];}if(new URL(entry.url).hostname==='my.mail.ru'&&/\/embed\/(\d+)/.test(entry.url)){const id=/\/embed\/(\d+)/.exec(entry.url)[1],data=await this.network.request('https://my.mail.ru/+/video/meta/'+id+'?ajax_call=1&ext=1',{signal,json:true,headers:{Referer:entry.url}});const videos=(data.videos||[]).map(video=>({...entry,url:absolute(video.url,entry.url),format:/\.m3u8(?:[?#]|$)/.test(video.url)?'hls':'mp4',name:entry.name+' '+(video.key||''),headers:{...entry.headers,Referer:entry.url}})).filter(v=>v.url);if(!videos.length)throw Error('MailRu : aucune vidéo publiée');return videos;}if(['hls','dash','mp4'].includes(entry.format)||/\.(m3u8|mpd|mp4)(?:[?#]|$)/i.test(entry.url))return [entry];if(depth>=5||visited.size>=16||visited.has(entry.url))throw Error('Chaîne de lecteurs non résolue');visited.add(entry.url);
  const data=await this.network.request(entry.url,{signal,headers:{Referer:entryURL.origin+'/',...entry.headers},mediaAware:true});if(data.mediaFormat)return [{...entry,url:data.url,format:data.mediaFormat}];const $=load(data.text);const urls=mediaCandidates(data.text);$('video[src],source[src]').each((_i,n)=>urls.push($(n).attr('src')));
  for(const script of $('script[type="application/json"]').toArray()){const decoded=decodeVoe($(script).text());if(decoded){const url=absolute(decoded.source,data.url);if(url)return [{...entry,url,format:'hls',headers:{...entry.headers,Referer:data.url,Origin:new URL(data.url).origin},subtitles:(decoded.captions||[]).map(c=>({url:absolute(c.file,data.url),label:c.label,language:c.language||'fr'})).filter(c=>c.url)}]}}
  const tape=streamtapeURL(data.text,data.url);if(tape)return [{...entry,url:tape,format:'mp4',headers:{...entry.headers,Referer:data.url}}];
  const pass=/['"](\/pass_md5\/[^'"]+)['"]/.exec(data.text)?.[1];if(pass){const address=new URL(pass,data.url),response=await this.network.request(address.href,{signal,ttl:0,headers:{Referer:data.url}}),prefix=response.text.trim();if(prefix.startsWith('https://'))return [{...entry,url:absolute(`${prefix}${require('node:crypto').randomBytes(8).toString('hex').slice(0,10)}?token=${encodeURIComponent(address.pathname.split('/').at(-1))}`,data.url),format:'mp4',headers:{Referer:new URL(data.url).origin}}];}
  for(const match of data.text.matchAll(/(?:\bSRC\b|\bfile\b|\bsource\b|\bvideo_url\b)\s*[:=]\s*["']([^"']+)["']/gi))urls.push(match[1].replace(/\\\//g,'/'));
  const direct=urls.map(x=>absolute(x,data.url)).filter(x=>/\.(mp4|m3u8|mpd)(?:[?#]|$)/i.test(x)).map(url=>({...entry,url,headers:{...entry.headers,Referer:data.url}}));if(direct.length)return direct;
  const candidates=playerSources(data.text).map(value=>absolute(value,data.url)).filter(url=>url&&!visited.has(url));if(candidates.length)return resolveServers(candidates.slice(0,4).map(url=>({...entry,url,headers:{...entry.headers,Referer:data.url}})),(candidate,task)=>this.extract(candidate,task,depth+1,visited),signal);const redirect=literalRedirect(data.text);if(redirect){const target=absolute(redirect,data.url);if(target)return this.extract({...entry,url:target,headers:{Referer:data.url}},signal,depth+1,visited);}const frames=$('iframe#thatframe[src],iframe[src],iframe[data-src]').toArray().map(n=>absolute($(n).attr('src')||$(n).attr('data-src'),data.url)).filter(Boolean);if(frames.length)return resolveServers(frames.slice(0,3).map(url=>({...entry,url,headers:{Referer:data.url}})),(frame,task)=>this.extract(frame,task,depth+1,visited),signal);throw Error('Lecteur sans média exposé ou validation requise');
 }
 async directory(signal){const entries=[];for(let page=1,last=1;page<=last;page++){const data=await this.network.request(`https://app.oustreamer.com/api/sites?per_page=100&page=${page}`,{signal,json:true});if(!data.success||!Array.isArray(data.data))throw Error('Annuaire invalide');last=Math.min(50,Number(data.meta?.last_page)||1);for(const item of data.data){const url=item.current_url?.url;if(['fr','multi'].includes(item.language)&&['films','series','anime','iptv','sport'].includes(item.category)&&url?.startsWith('https://'))entries.push({name:item.name,slug:item.slug,url,status:item.status})}}return entries;}
}
module.exports={Providers,parseM3U,parseCards,samaPlayers,samaSeasons,DEFINITIONS};
