const net=require('node:net');const os=require('node:os');const crypto=require('node:crypto');
const MAX_FRAME=1024*1024;
function frame(value){const body=Buffer.from(typeof value==='string'?value:JSON.stringify(value));if(body.length>MAX_FRAME)throw Error('Trame trop volumineuse');const head=Buffer.alloc(4);head.writeUInt32BE(body.length);return Buffer.concat([head,body]);}
function readFrame(socket,callback){let bytes=Buffer.alloc(0),done=false;socket.on('data',chunk=>{if(done)return;bytes=Buffer.concat([bytes,chunk]);if(bytes.length>MAX_FRAME+4){done=true;socket.destroy();return}if(bytes.length<4)return;const size=bytes.readUInt32BE();if(size<1||size>MAX_FRAME){done=true;socket.destroy();return}if(bytes.length>=size+4){done=true;callback(bytes.subarray(4,4+size).toString('utf8'))}});}
function privateIPv4(host){return /^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(host)&&net.isIP(host)===4;}
function parsePair(raw){let uri;try{uri=new URL(raw)}catch{throw Error('Code d’association local invalide')} const host=uri.searchParams.get('host'),token=uri.searchParams.get('token');if(uri.protocol!=='tvsama:'||uri.hostname!=='pair'||!privateIPv4(host)||!/^[a-zA-Z0-9]{12,64}$/.test(token||''))throw Error('Code d’association local invalide');return {host,token};}
class Remote {
 constructor(store,onCommand,{connect=net.connect}={}){this.connect=connect;this.store=store;this.onCommand=onCommand;this.playback={title:'',position:0,duration:0,playing:false};this.sockets=new Set();}
 async start(port=28743,host='0.0.0.0'){if(this.server)return;this.token=this.store.state.pairingToken||crypto.randomBytes(16).toString('hex');this.store.state.pairingToken=this.token;await this.store.save(this.store.state);
   this.server=net.createServer(socket=>{if(this.sockets.size>=16){socket.destroy();return}this.sockets.add(socket);socket.on('close',()=>this.sockets.delete(socket));socket.on('error',()=>{});socket.setTimeout(4000,()=>socket.destroy());readFrame(socket,async raw=>{try{const command=JSON.parse(raw);if(command.token!==this.token)throw Error('Non autorisé');if(!['pair','search','play','preload','sync','toggle','seek','previous','next','episode','sleep'].includes(command.action))throw Error('Commande inconnue');
    if(['play','preload'].includes(command.action)&&(!command.sources?.length||command.sources.some(s=>!/^https:\/\//.test(s.url))))throw Error('Sources invalides');
    if(command.action==='sync'){const core=require('../core/library.js');core.mergeHistory(this.store.state,(command.history||[]).slice(0,200));for(const [key,time]of Object.entries(command.hidden||{})){if(Number.isFinite(time))this.store.state.hidden[key]=Math.max(this.store.state.hidden[key]||0,time)}await this.store.save(this.store.state);this.onCommand({action:'librarySync',history:this.store.state.history,hidden:this.store.state.hidden});socket.end(frame({playback:this.playback,history:this.store.state.history.slice(0,100),hidden:this.store.state.hidden}));}
    else {if(command.action!=='pair')this.onCommand(command);socket.end(frame('OK'));}
   }catch{socket.destroy()}})});try{await new Promise((resolve,reject)=>{this.server.once('error',reject);this.server.listen(port,host,resolve)})}catch(e){this.server.close();this.server=null;throw e}
 }
 url(){const host=Object.values(os.networkInterfaces()).flat().find(i=>!i.internal&&i.family==='IPv4'&&privateIPv4(i.address))?.address;if(!host)throw Error('Aucun réseau local IPv4');const url=new URL('tvsama://pair');url.search=new URLSearchParams({host,token:this.token,device:os.hostname()}).toString();return url.href;}
 async exchange(target,command,port=28743){if(!privateIPv4(target.host))throw Error('Hôte local requis');return new Promise((resolve,reject)=>{const socket=this.connect(port,target.host);socket.on('close',()=>reject(Error('Appareil déconnecté sans réponse')));socket.on('end',()=>reject(Error('Appareil déconnecté sans réponse')));socket.setTimeout(4000,()=>socket.destroy(Error('Télévision injoignable')));socket.on('error',reject);socket.on('connect',()=>socket.write(frame({...command,token:target.token})));readFrame(socket,raw=>{socket.end();if(command.action==='sync'){try{resolve(JSON.parse(raw))}catch(e){reject(e)}}else raw==='OK'?resolve(true):reject(Error('Télévision occupée'))})});}
 async close(){for(const socket of this.sockets)socket.destroy();if(this.server)await new Promise(resolve=>this.server.close(resolve));this.server=null;}
}
module.exports={Remote,frame,readFrame,parsePair,privateIPv4};
