const fs=require('node:fs/promises');const path=require('node:path');const crypto=require('node:crypto');
const ROOT='https://api.github.com/repos/Leonwaar/TvSama/releases/latest';
function releaseURL(raw){const u=new URL(raw);if(u.protocol!=='https:'||u.hostname!=='github.com'||!u.pathname.startsWith('/Leonwaar/TvSama/releases/download/'))throw Error('Origine de mise à jour non autorisée');return u.href;}
class Updates{
 constructor(network,fetcher){this.network=network;this.fetcher=fetcher;this.busy=false;}
 async check(){const data=await this.network.request(ROOT,{json:true,ttl:60000}),asset=data.assets?.find(a=>/Windows-x64\.exe$/i.test(a.name));return {version:data.tag_name,url:asset?releaseURL(asset.browser_download_url):'',name:asset?.name||'',digest:/^sha256:[a-f0-9]{64}$/i.test(asset?.digest||'')?asset.digest.slice(7).toLowerCase():'',size:asset?.size||0};}
 async download(destination){if(this.busy)throw Error('Téléchargement déjà en cours');this.busy=true;const temporary=`${destination}.download`;let file;try{const info=await this.check();if(!info.url||!info.digest)throw Error('Aucune empreinte SHA-256 publiée pour cet EXE : téléchargement vérifié indisponible');if(info.size<=0||info.size>350*1024*1024)throw Error('Taille de mise à jour invalide');const response=await this.fetcher(info.url,{redirect:'follow',signal:AbortSignal.timeout(180000)});if(!response.ok)throw Error(`HTTP ${response.status}`);const final=new URL(response.url||info.url);if(final.protocol!=='https:'||!['github.com','release-assets.githubusercontent.com','objects.githubusercontent.com'].includes(final.hostname))throw Error('Redirection de téléchargement invalide');file=await fs.open(temporary,'wx',0o600);let size=0;const hash=crypto.createHash('sha256');for await(const bytes of response.body){size+=bytes.byteLength;if(size>info.size)throw Error('Taille téléchargée incorrecte');hash.update(bytes);let offset=0;while(offset<bytes.byteLength){const result=await file.write(bytes,offset,bytes.byteLength-offset);offset+=result.bytesWritten;}}await file.close();file=null;if(size!==info.size||hash.digest('hex')!==info.digest)throw Error('Empreinte SHA-256 incorrecte');await fs.rename(temporary,destination);return {file:path.basename(destination),version:info.version,sha256:info.digest};}finally{await file?.close().catch(()=>{});await fs.rm(temporary,{force:true}).catch(()=>{});this.busy=false;}}
}
module.exports={Updates,releaseURL};
